In [1]:
import pandas as pd
import numpy as np

In [2]:
#Create the dataset
data = {
    "Name": ["Akash", "Priya", "Rahul", "Sneha", "Arjun",
             "Kavya", "Rohan", "Anjali", "Vijay", "Meena"],

    "Maths": [85, 92, 67, 95, 74, 88, 56, 90, 72, 96],
    "Science": [78, 89, 70, 94, 80, 91, 60, 87, 75, 98],
    "English": [82, 95, 65, 90, 78, 85, 62, 92, 70, 94],
    "Attendance": [90, 95, 75, 98, 80, 92, 65, 96, 78, 99]
}

df = pd.DataFrame(data)

df

     Name  Maths  Science  English  Attendance
0   Akash     85       78       82          90
1   Priya     92       89       95          95
2   Rahul     67       70       65          75
3   Sneha     95       94       90          98
4   Arjun     74       80       78          80
5   Kavya     88       91       85          92
6   Rohan     56       60       62          65
7  Anjali     90       87       92          96
8   Vijay     72       75       70          78
9   Meena     96       98       94          99

In [3]:
#Explore the data
print("First five rows:")
display(df.head())

print("Dataset information:")
df.info()

print("Statistical summary:")
display(df.describe())

First five rows:

    Name  Maths  Science  English  Attendance
0  Akash     85       78       82          90
1  Priya     92       89       95          95
2  Rahul     67       70       65          75
3  Sneha     95       94       90          98
4  Arjun     74       80       78          80

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     str
 1   Maths       10 non-null     int64
 2   Science     10 non-null     int64
 3   English     10 non-null     int64
 4   Attendance  10 non-null     int64
dtypes: int64(4), str(1)
memory usage: 532.0 bytes
Statistical summary:

           Maths    Science    English  Attendance
count  10.000000  10.000000  10.000000   10.000000
mean   81.500000  82.200000  81.300000   86.800000
std    13.484559  11.792653  12.156845   11.554701
min    56.000000  60.000000  62.000000   65.000000
25%    72.500000  75.750000  72.000000   78.500000
50%    86.500000  83.500000  83.500000   91.000000
75%    91.500000  90.500000  91.500000   95.750000
max    96.000000  98.000000  95.000000   99.000000

In [4]:
#Calculate total and average marks
df["Total"] = df[["Maths", "Science", "English"]].sum(axis=1)

df["Average"] = df[["Maths", "Science", "English"]].mean(axis=1)

display(df)

     Name  Maths  Science  English  Attendance  Total    Average
0   Akash     85       78       82          90    245  81.666667
1   Priya     92       89       95          95    276  92.000000
2   Rahul     67       70       65          75    202  67.333333
3   Sneha     95       94       90          98    279  93.000000
4   Arjun     74       80       78          80    232  77.333333
5   Kavya     88       91       85          92    264  88.000000
6   Rohan     56       60       62          65    178  59.333333
7  Anjali     90       87       92          96    269  89.666667
8   Vijay     72       75       70          78    217  72.333333
9   Meena     96       98       94          99    288  96.000000

In [5]:
#Assign grades
def calculate_grade(average):
    if average >= 90:
        return "A"
    elif average >= 80:
        return "B"
    elif average >= 70:
        return "C"
    elif average >= 60:
        return "D"
    else:
        return "F"

df["Grade"] = df["Average"].apply(calculate_grade)

display(df[["Name", "Average", "Grade"]])

     Name    Average Grade
0   Akash  81.666667     B
1   Priya  92.000000     A
2   Rahul  67.333333     D
3   Sneha  93.000000     A
4   Arjun  77.333333     C
5   Kavya  88.000000     B
6   Rohan  59.333333     F
7  Anjali  89.666667     B
8   Vijay  72.333333     C
9   Meena  96.000000     A

In [6]:
#Find the top-performing students
top_students = df.sort_values(
    by="Average",
    ascending=False
)

display(top_students[["Name", "Average", "Grade"]].head(3))

    Name  Average Grade
9  Meena     96.0     A
3  Sneha     93.0     A
1  Priya     92.0     A

In [7]:
#Find students who need improvement
low_performers = df[df["Average"] < 70]

print("Students who need improvement:")
display(low_performers[["Name", "Average", "Grade"]])

Students who need improvement:

    Name    Average Grade
2  Rahul  67.333333     D
6  Rohan  59.333333     F

In [8]:
#Compare subject averages
subjects = ["Maths", "Science", "English"]

subject_averages = df[subjects].mean()

print("Average marks in each subject:")
display(subject_averages)

Average marks in each subject:

Maths      81.5
Science    82.2
English    81.3
dtype: float64

In [9]:
#Analyze attendance
low_attendance = df[df["Attendance"] < 75]

print("Students with attendance below 75%:")
display(low_attendance[["Name", "Attendance"]])

Students with attendance below 75%:

    Name  Attendance
6  Rohan          65

In [10]:
#Export the analyzed dataset
df.to_csv("student_performance_results.csv", index=False)

print("Analysis saved successfully!")

Analysis saved successfully!